[package]
name = "abc277c"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
cli_test_dir = "*"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
itertools = {version = "=0.9.0"}
